FROM golang:1.18.6 AS base 
WORKDIR /usr/src/app/
COPY ./ ./
RUN go build -o http-server ./server/*.go

FROM golang:1.18.6 AS http-server
WORKDIR /usr/src/app/
COPY --from=base /usr/src/app/http-server ./
ENTRYPOINT [ "./http-server" ]


