version: "3.7"

networks:
  default:
    name: demo
    driver: bridge

services:
  phlare:
    image: grafana/phlare:0.1.0
    command:
      - --config.file=/etc/phlare/config.yaml
    volumes:
      - ./phlare/config.yaml:/etc/phlare/config.yaml
    ports:
      - "4100:4100"

  grafana:
    image: grafana/grafana:main
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph 
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
