version: "3.7"

networks:
  default:
    name: demo
    driver: bridge

services:
  prometheus-0:
    image: quay.io/prometheus/prometheus:v2.42.0
    command: 
    - --web.console.templates=/etc/prometheus/consoles
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --storage.tsdb.retention.time=20m
    - --config.file=/etc/prometheus-config.yaml
    - --storage.tsdb.path=/prometheus
    - --web.enable-lifecycle
    - --web.route-prefix=/
    - --enable-feature=promql-per-step-stats
    volumes:
    - ./prometheus-config.yaml:/etc/prometheus-config.yaml
    - prometheus-0-db:/prometheus
    ports:
    - "9090:9090"
  
  thanos-sidecar-0: 
    image: quay.io/thanos/thanos:v0.31.0-rc.0
    volumes:
    - prometheus-0-db:/prometheus
    - ./trace-config.yaml:/etc/trace-config.yaml
    command: 
    - sidecar
    - --tsdb.path=/prometheus
    - --prometheus.url=http://prometheus-0:9090 
    - --tracing.config-file=/etc/trace-config.yaml
    expose:
      - 10901
    depends_on:
      - prometheus-0

  thanos-query:
    image: quay.io/thanos/thanos:v0.31.0-rc.0
    command: 
    - query
    - --http-address=0.0.0.0:10900
    - --store=thanos-sidecar-0:10901
    - --tracing.config-file=/etc/trace-config.yaml
    - --query.promql-engine=thanos
    volumes:
    - ./trace-config.yaml:/etc/trace-config.yaml
    ports:
    - "10900:10900"

  jaeger:
    image: jaegertracing/all-in-one:1.42
    command: 
    - --memory.max-traces=10000
    environment:
    - COLLECTOR_OTLP_ENABLED=true
    ports:
    - "4317:4317"
    - "16686:16686"

  avalanche:
    image: quay.io/freshtracks.io/avalanche:latest
    ports:
      - "9001:9001"

volumes:
  prometheus-0-db: