FROM golang:1.18.6 AS base 
WORKDIR /usr/src/app/
COPY ./ ./
RUN go env -w GOPROXY=https://goproxy.cn
RUN go build -o http-server server/main.go

FROM golang:1.18.6 AS server
WORKDIR /usr/src/app/
COPY --from=base /usr/src/app/http-server ./
ENTRYPOINT [ "./http-server" ]