kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  APIServerTracing: true
  KubeletTracing: true
nodes:
- role: control-plane
  image: kindest/node:v1.25.3
  extraMounts:
    - hostPath: ./jaeger.yaml
      containerPath: /etc/kubernetes/manifests/jaeger.yaml
    - hostPath: ./prometheus.yaml
      containerPath: /etc/kubernetes/manifests/prometheus.yaml
    - hostPath: ./prometheus-config.yaml
      containerPath: /etc/prometheus-config.yaml
        
