apiVersion: v1
kind: Pod
metadata:
  labels:
    component: prometheus
  name: prometheus
  namespace: kube-system
spec:
  containers:
  - args:
    - --web.console.templates=/etc/prometheus/consoles
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --storage.tsdb.retention.time=20m
    - --config.file=/etc/prometheus-config.yaml
    - --storage.tsdb.path=/prometheus
    - --web.enable-lifecycle
    - --web.route-prefix=/
    # image: quay.io/prometheus/prometheus:v2.42.0
    image: fatsheep9146/prometheus:v2.42.0
    imagePullPolicy: IfNotPresent
    name: prometheus
    securityContext:
      runAsUser: 0
    volumeMounts:
    - mountPath: /etc/prometheus-config.yaml
      name: config
      readOnly: true
    - mountPath: /etc/kubernetes
      name: k8s-certs
      readOnly: true
  hostNetwork: true
  priorityClassName: system-node-critical
  volumes:
  - hostPath:
      path: /etc/prometheus-config.yaml
      type: File
    name: config
  - hostPath:
      path: /etc/kubernetes
      type: DirectoryOrCreate
    name: k8s-certs